// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbgen

import (
	"database/sql"
	"time"
)

type Game struct {
	ID          string
	Name        string
	Description string
	Technology  string
	ReleaseDate time.Time
	Likes       int64
	Votes       int64
	GameUrl     sql.NullString
}

type GameTag struct {
	GameID string
	TagID  int64
}

type Tag struct {
	TagID int64
	Tag   string
}
