// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Admin struct {
	ID       int32
	Username string
	Password string
	Role     string
}

type Game struct {
	ID          string
	Name        string
	Description string
	Technology  string
	ReleaseDate pgtype.Date
	Likes       int32
	Votes       int32
	GameUrl     pgtype.Text
}

type GameTag struct {
	GameID string
	TagID  int32
}

type Tag struct {
	TagID int32
	Tag   string
}
