// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbgen

import (
	"database/sql"
)

type Game struct {
	ID           string
	Name         string
	Description  string
	Technology   string
	ReleaseDate  sql.NullTime
	Likes        sql.NullInt64
	Votes        sql.NullInt64
	ThumbnailUrl string
	GifUrl       string
	GameUrl      string
}
