// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package dbgen

import (
	"context"
	"database/sql"
)

const addGame = `-- name: AddGame :one
INSERT INTO
    Game(id, name, description, technology, game_url)
VALUES
    (?, ?, ?, ?, ?) RETURNING id, name, description, technology, release_date, likes, votes, game_url
`

type AddGameParams struct {
	ID          string
	Name        string
	Description string
	Technology  string
	GameUrl     sql.NullString
}

func (q *Queries) AddGame(ctx context.Context, arg AddGameParams) (Game, error) {
	row := q.db.QueryRowContext(ctx, addGame,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Technology,
		arg.GameUrl,
	)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Technology,
		&i.ReleaseDate,
		&i.Likes,
		&i.Votes,
		&i.GameUrl,
	)
	return i, err
}

const deleteGameById = `-- name: DeleteGameById :one
DELETE FROM
    Game
WHERE
    id = ? RETURNING id, name, description, technology, release_date, likes, votes, game_url
`

func (q *Queries) DeleteGameById(ctx context.Context, id string) (Game, error) {
	row := q.db.QueryRowContext(ctx, deleteGameById, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Technology,
		&i.ReleaseDate,
		&i.Likes,
		&i.Votes,
		&i.GameUrl,
	)
	return i, err
}

const getGameByName = `-- name: GetGameByName :one
SELECT
    id, name, description, technology, release_date, likes, votes, game_url
FROM
    Game
WHERE
    name = ?
`

func (q *Queries) GetGameByName(ctx context.Context, name string) (Game, error) {
	row := q.db.QueryRowContext(ctx, getGameByName, name)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Technology,
		&i.ReleaseDate,
		&i.Likes,
		&i.Votes,
		&i.GameUrl,
	)
	return i, err
}

const getGameIdByName = `-- name: GetGameIdByName :one
SELECT
    id
FROM
    Game
WHERE
    name = ?
`

func (q *Queries) GetGameIdByName(ctx context.Context, name string) (string, error) {
	row := q.db.QueryRowContext(ctx, getGameIdByName, name)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getNewGames = `-- name: GetNewGames :many
SELECT
    id, name, description, technology, release_date, likes, votes, game_url
FROM
    Game
ORDER BY
    release_date
LIMIT
    10
`

func (q *Queries) GetNewGames(ctx context.Context) ([]Game, error) {
	rows, err := q.db.QueryContext(ctx, getNewGames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Game
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Technology,
			&i.ReleaseDate,
			&i.Likes,
			&i.Votes,
			&i.GameUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPopularGames = `-- name: GetPopularGames :many
SELECT
    id, name, description, technology, release_date, likes, votes, game_url
FROM
    Game
ORDER BY
    votes DESC
LIMIT
    10
`

func (q *Queries) GetPopularGames(ctx context.Context) ([]Game, error) {
	rows, err := q.db.QueryContext(ctx, getPopularGames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Game
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Technology,
			&i.ReleaseDate,
			&i.Likes,
			&i.Votes,
			&i.GameUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopRatedGames = `-- name: GetTopRatedGames :many
SELECT
    id, name, description, technology, release_date, likes, votes, game_url
FROM
    Game
ORDER BY
    (likes / votes) DESC
LIMIT
    10
`

func (q *Queries) GetTopRatedGames(ctx context.Context) ([]Game, error) {
	rows, err := q.db.QueryContext(ctx, getTopRatedGames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Game
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Technology,
			&i.ReleaseDate,
			&i.Likes,
			&i.Votes,
			&i.GameUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
